[package]
name='ode_wasm'
version='0.1.0'
edition='2021'

[lib]
crate-type=['cdylib','rlib']

[dependencies]
wasm-bindgen='0.2'
ode_solvers='0.5'
serde={version='1', features=['derive']}
serde_wasm_bindgen='0.6'

[profile.release]
opt-level='s'
lto=true
codegen-units=1
